# docker-compose.yml
version: '3.8'

services:
  db:
    image: postgres:16-alpine # Using a lightweight PostgreSQL image
    restart: always
    environment:
      POSTGRES_DB: tastybites_db # Your database name
      POSTGRES_USER: tastybites_user # Your database user
      POSTGRES_PASSWORD: password # Your database password
    ports:
      - '5432:5432' # Maps host port 5432 to container port 5432
    volumes:
      - db_data:/var/lib/postgresql/data # Persist database data

volumes:
  db_data: # Define the named volume for data persistence

